### ISSUE TITLE
not responding on macOS Big Sur

### ISSUE THREAD

**Issue by burstchao** [IENT/YUView#290]
is it incompatible?

**Comment by ekremcet** [comment]
Hi, I had the same error when I used the release version. Cloning the project and building from the repository solved this issue for me

**Comment by ChristianFeldmann** [comment]
Hi. 
That is strange. We are building the release version on an older Mac version so mayber there is some incompatibility there. I will see if we can update the environment. For now it looks like building YUView from source seems to be the solution. What Qt version did you use to build?

**Comment by ekremcet** [comment]
Hi Christian,

I used QT 5.15.0 . However, there is another problem here. When I open x265 file it does not show the encoding information (CTU, motion vectors, etc.). It was working fine before the BigSur update

Thanks

> Hi.
> That is strange. We are building the release version on an older Mac version so mayber there is some incompatibility there. I will see if we can update the environment. For now it looks like building YUView from source seems to be the solution. What Qt version did you use to build?

**Comment by ChristianFeldmann** [comment]
Does it show the checkboxes to select the information at least? Or is the list of checkboxes even empty?

**Comment by ekremcet** [comment]
No, it does not show. I leave the screenshot here:

![image](https://user-images.githubusercontent.com/16050225/99383498-3c00ee00-28ce-11eb-9ad5-d2610c4f7641.png)

**Comment by ChristianFeldmann** [comment]
Ok interesting. Because that means that YUView was not able to open the statistics interface in libde265. Do you have any other version of libde265 installed or in your system paths? Because only the one that we ship with YUView support the statistics feature.

**Comment by ekremcet** [comment]
I don't think I have another version of libde265 in my system, but I am not sure. Do you know how can I check that?

**Comment by ChristianFeldmann** [comment]
You could search in your local filesystem linux style:
```
find / -name "libde265*"
```
Unfortunately YUView does not always report the path to the library it used correctly. That could be enhanced. 
Another test that would really help:
 - Get the dylib mac build from here: https://github.com/ChristianFeldmann/libde265/releases
 - In YUView go to settings->decoder and select this downloaded file manually
 - Re-try to open a raw hevc file to see if it works now
Because that libde265 version should definitely have the statistics feature. And if that does not work then maybe something else is wrong. Maybe apple changed something about how libraries are opened ...

**Comment by ekremcet** [comment]
Thanks, downloading the dylib build and specifying the path in the YUView settings solved the issue. And sorry for the late reply :)

**Comment by ChristianFeldmann** [comment]
I just looked at the Github Actions build pipeline that we use and MacOS Big Sur 11.0 is now also supported as a preview. So I will try to build it with the new version. Maybe that solves this issue. And I will have to test backwards compatibility. But I'll leave this issue open for that test.

**Comment by ChristianFeldmann** [comment]
So I
 - updated Qt to the latest 5.15.1
 - Added a build to YUView on Mac Os Big-Sur. Github Actions already supports this.

@ekremcet I could need your help as you seem to have a Mac device with BigSur installed. I unfortunately don't have access to one. Here is the latest build in Github Actions: https://github.com/IENT/YUView/runs/1447806159?check_suite_focus=true
On the top right on that page should be an `artifacts` button where you can download the built artifacts. Could you test the macOS build and the macOS-BigSur build? That would help a lot!

**Comment by ekremcet** [comment]
Hi @ChristianFeldmann ,

So I tried both macOS and macOS-BigSur builds and this time both of them worked fine. No freezing and I could see the statistics with libde265 without setting the decoder manually. However, this time UI texts are a bit blurred. I think it was solved in #194 but for some reason, it is back with these new versions you mentioned. I leave a screenshot below. Thanks

<img width="1741" alt="Screenshot 2020-11-25 at 09 23 13" src="https://user-images.githubusercontent.com/16050225/100201418-51929b00-2f00-11eb-9265-a87e268e477b.png">

**Comment by ChristianFeldmann** [comment]
Very nice. I think then we can stay with the build on Mac OS 10.15 for now. I just have a hunch that building on MacOS BigSur may create some issues on older MacOs versions. Although I tested the new build also on a quite old version and that one was fine.
Yes the blurry issue is still in this version because I did not merge that PR yet when this version was built. But I will double-check with the latest version. Thank you for testing!
